from ._constants import Capabilities, ScmpAction, ScmpArch, ScmpCmp
from ._libseccomp import ScmpArg

__all__ = ("SUB_ARCHITECTURES",)

# https://src.fedoraproject.org/rpms/containers-common/blob/f34/f/seccomp.json
SUB_ARCHITECTURES = {
    ScmpArch.SCMP_ARCH_X86: [ScmpArch.SCMP_ARCH_X86_64, ScmpArch.SCMP_ARCH_X32],
    ScmpArch.SCMP_ARCH_X86_64: [ScmpArch.SCMP_ARCH_X86, ScmpArch.SCMP_ARCH_X32],
    ScmpArch.SCMP_ARCH_X32: [ScmpArch.SCMP_ARCH_X86_64, ScmpArch.SCMP_ARCH_X86],
    ScmpArch.SCMP_ARCH_AARCH64: [ScmpArch.SCMP_ARCH_ARM],
    ScmpArch.SCMP_ARCH_MIPS64: [ScmpArch.SCMP_ARCH_MIPS, ScmpArch.SCMP_ARCH_MIPS64N32],
    ScmpArch.SCMP_ARCH_MIPS64N32: [ScmpArch.SCMP_ARCH_MIPS, ScmpArch.SCMP_ARCH_MIPS64],
    ScmpArch.SCMP_ARCH_MIPSEL64: [
        ScmpArch.SCMP_ARCH_MIPSEL,
        ScmpArch.SCMP_ARCH_MIPSEL64N32,
    ],
    ScmpArch.SCMP_ARCH_MIPSEL64N32: [
        ScmpArch.SCMP_ARCH_MIPSEL,
        ScmpArch.SCMP_ARCH_MIPSEL64,
    ],
    ScmpArch.SCMP_ARCH_S390X: [ScmpArch.SCMP_ARCH_S390],
}

DEFAULT_ACTION = ScmpAction.SCMP_ACT_ERRNO

SYSCALLS = [
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "names": [
            "_llseek",
            "_newselect",
            "accept",
            "accept4",
            "access",
            "adjtimex",
            "alarm",
            "bind",
            "brk",
            "capget",
            "capset",
            "chdir",
            "chmod",
            "chown",
            "chown32",
            "clock_adjtime",
            "clock_adjtime64",
            "clock_getres",
            "clock_getres_time64",
            "clock_gettime",
            "clock_gettime64",
            "clock_nanosleep",
            "clock_nanosleep_time64",
            "clone",
            "close",
            "connect",
            "copy_file_range",
            "creat",
            "dup",
            "dup2",
            "dup3",
            "epoll_create",
            "epoll_create1",
            "epoll_ctl",
            "epoll_ctl_old",
            "epoll_pwait",
            "epoll_wait",
            "epoll_wait_old",
            "eventfd",
            "eventfd2",
            "execve",
            "execveat",
            "exit",
            "exit_group",
            "faccessat",
            "faccessat2",
            "fadvise64",
            "fadvise64_64",
            "fallocate",
            "fanotify_mark",
            "fchdir",
            "fchmod",
            "fchmodat",
            "fchown",
            "fchown32",
            "fchownat",
            "fcntl",
            "fcntl64",
            "fdatasync",
            "fgetxattr",
            "flistxattr",
            "flock",
            "fork",
            "fremovexattr",
            "fsetxattr",
            "fstat",
            "fstat64",
            "fstatat64",
            "fstatfs",
            "fstatfs64",
            "fsync",
            "ftruncate",
            "ftruncate64",
            "futex",
            "futimesat",
            "get_robust_list",
            "get_thread_area",
            "getcpu",
            "getcwd",
            "getdents",
            "getdents64",
            "getegid",
            "getegid32",
            "geteuid",
            "geteuid32",
            "getgid",
            "getgid32",
            "getgroups",
            "getgroups32",
            "getitimer",
            "getpeername",
            "getpgid",
            "getpgrp",
            "getpid",
            "getppid",
            "getpriority",
            "getrandom",
            "getresgid",
            "getresgid32",
            "getresuid",
            "getresuid32",
            "getrlimit",
            "getrusage",
            "getsid",
            "getsockname",
            "getsockopt",
            "gettid",
            "gettimeofday",
            "getuid",
            "getuid32",
            "getxattr",
            "inotify_add_watch",
            "inotify_init",
            "inotify_init1",
            "inotify_rm_watch",
            "io_cancel",
            "io_destroy",
            "io_getevents",
            "io_setup",
            "io_submit",
            "ioctl",
            "ioprio_get",
            "ioprio_set",
            "ipc",
            "keyctl",
            "kill",
            "lchown",
            "lchown32",
            "lgetxattr",
            "link",
            "linkat",
            "listen",
            "listxattr",
            "llistxattr",
            "lremovexattr",
            "lseek",
            "lsetxattr",
            "lstat",
            "lstat64",
            "madvise",
            "memfd_create",
            "mincore",
            "mkdir",
            "mkdirat",
            "mknod",
            "mknodat",
            "mlock",
            "mlock2",
            "mlockall",
            "mmap",
            "mmap2",
            "mount",
            "mprotect",
            "mq_getsetattr",
            "mq_notify",
            "mq_open",
            "mq_timedreceive",
            "mq_timedsend",
            "mq_unlink",
            "mremap",
            "msgctl",
            "msgget",
            "msgrcv",
            "msgsnd",
            "msync",
            "munlock",
            "munlockall",
            "munmap",
            "name_to_handle_at",
            "nanosleep",
            "newfstatat",
            "open",
            "openat",
            "openat2",
            "pause",
            "pidfd_getfd",
            "pipe",
            "pipe2",
            "pivot_root",
            "poll",
            "ppoll",
            "ppoll_time64",
            "prctl",
            "pread64",
            "preadv",
            "preadv2",
            "prlimit64",
            "pselect6",
            "pselect6_time64",
            "pwrite64",
            "pwritev",
            "pwritev2",
            "read",
            "readahead",
            "readlink",
            "readlinkat",
            "readv",
            "reboot",
            "recv",
            "recvfrom",
            "recvmmsg",
            "recvmsg",
            "remap_file_pages",
            "removexattr",
            "rename",
            "renameat",
            "renameat2",
            "restart_syscall",
            "rmdir",
            "rt_sigaction",
            "rt_sigpending",
            "rt_sigprocmask",
            "rt_sigqueueinfo",
            "rt_sigreturn",
            "rt_sigsuspend",
            "rt_sigtimedwait",
            "rt_tgsigqueueinfo",
            "sched_get_priority_max",
            "sched_get_priority_min",
            "sched_getaffinity",
            "sched_getattr",
            "sched_getparam",
            "sched_getscheduler",
            "sched_rr_get_interval",
            "sched_setaffinity",
            "sched_setattr",
            "sched_setparam",
            "sched_setscheduler",
            "sched_yield",
            "seccomp",
            "select",
            "semctl",
            "semget",
            "semop",
            "semtimedop",
            "send",
            "sendfile",
            "sendfile64",
            "sendmmsg",
            "sendmsg",
            "sendto",
            "set_robust_list",
            "set_thread_area",
            "set_tid_address",
            "setfsgid",
            "setfsgid32",
            "setfsuid",
            "setfsuid32",
            "setgid",
            "setgid32",
            "setgroups",
            "setgroups32",
            "setitimer",
            "setpgid",
            "setpriority",
            "setregid",
            "setregid32",
            "setresgid",
            "setresgid32",
            "setresuid",
            "setresuid32",
            "setreuid",
            "setreuid32",
            "setrlimit",
            "setsid",
            "setsockopt",
            "setuid",
            "setuid32",
            "setxattr",
            "shmat",
            "shmctl",
            "shmdt",
            "shmget",
            "shutdown",
            "sigaltstack",
            "signalfd",
            "signalfd4",
            "sigreturn",
            "socket",
            "socketcall",
            "socketpair",
            "splice",
            "stat",
            "stat64",
            "statfs",
            "statfs64",
            "statx",
            "symlink",
            "symlinkat",
            "sync",
            "sync_file_range",
            "syncfs",
            "sysinfo",
            "syslog",
            "tee",
            "tgkill",
            "time",
            "timer_create",
            "timer_delete",
            "timer_getoverrun",
            "timer_gettime",
            "timer_gettime64",
            "timer_settime",
            "timerfd_create",
            "timerfd_gettime",
            "timerfd_gettime64",
            "timerfd_settime",
            "timerfd_settime64",
            "times",
            "tkill",
            "truncate",
            "truncate64",
            "ugetrlimit",
            "umask",
            "umount",
            "umount2",
            "uname",
            "unlink",
            "unlinkat",
            "unshare",
            "utime",
            "utimensat",
            "utimensat_time64",
            "utimes",
            "vfork",
            "vmsplice",
            "wait4",
            "waitid",
            "waitpid",
            "write",
            "writev",
        ],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(0, ScmpCmp.SCMP_CMP_EQ, 0, 0)],
        "names": ["personality"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(0, ScmpCmp.SCMP_CMP_EQ, 8, 0)],
        "names": ["personality"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(0, ScmpCmp.SCMP_CMP_EQ, 131072, 0)],
        "names": ["personality"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(0, ScmpCmp.SCMP_CMP_EQ, 131080, 0)],
        "names": ["personality"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(0, ScmpCmp.SCMP_CMP_EQ, 4294967295, 0)],
        "names": ["personality"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"arches": [ScmpArch.SCMP_ARCH_PPC64LE]},
        "names": ["sync_file_range2"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"arches": [ScmpArch.SCMP_ARCH_ARM, ScmpArch.SCMP_ARCH_AARCH64]},
        "names": [
            "arm_fadvise64_64",
            "arm_sync_file_range",
            "sync_file_range2",
            "breakpoint",
            "cacheflush",
            "set_tls",
        ],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"arches": [ScmpArch.SCMP_ARCH_X86_64, ScmpArch.SCMP_ARCH_X32]},
        "names": ["arch_prctl"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {
            "arches": [
                ScmpArch.SCMP_ARCH_X86_64,
                ScmpArch.SCMP_ARCH_X32,
                ScmpArch.SCMP_ARCH_X86,
            ]
        },
        "names": ["modify_ldt"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"arches": [ScmpArch.SCMP_ARCH_S390, ScmpArch.SCMP_ARCH_S390X]},
        "names": ["s390_pci_mmio_read", "s390_pci_mmio_write", "s390_runtime_instr"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_DAC_READ_SEARCH]},
        "names": ["open_by_handle_at"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_ADMIN]},
        "names": [
            "bpf",
            "clone",
            "fanotify_init",
            "lookup_dcookie",
            "mount",
            "name_to_handle_at",
            "perf_event_open",
            "quotactl",
            "setdomainname",
            "sethostname",
            "setns",
            "umount",
            "umount2",
            "unshare",
        ],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(0, ScmpCmp.SCMP_CMP_MASKED_EQ, 2080505856, 0)],
        "excludes": {
            "arches": [ScmpArch.SCMP_ARCH_S390, ScmpArch.SCMP_ARCH_S390X],
            "caps": [Capabilities.CAP_SYS_ADMIN],
        },
        "names": ["clone"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(1, ScmpCmp.SCMP_CMP_MASKED_EQ, 2080505856, 0)],
        "comment": "s390 parameter ordering for clone is different",
        "excludes": {"caps": [Capabilities.CAP_SYS_ADMIN]},
        "includes": {"arches": [ScmpArch.SCMP_ARCH_S390, ScmpArch.SCMP_ARCH_S390X]},
        "names": ["clone"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_BOOT]},
        "names": ["reboot"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_CHROOT]},
        "names": ["chroot"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_MODULE]},
        "names": ["delete_module", "init_module", "finit_module", "query_module"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_NICE]},
        "names": ["get_mempolicy", "mbind", "name_to_handle_at", "set_mempolicy"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_PACCT]},
        "names": ["acct"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_PTRACE]},
        "names": ["kcmp", "process_vm_readv", "process_vm_writev", "ptrace"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_RAWIO]},
        "names": ["iopl", "ioperm"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_TIME]},
        "names": ["settimeofday", "stime", "clock_settime", "clock_settime64"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_SYS_TTY_CONFIG]},
        "names": ["vhangup"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ERRNO,
        "args": [
            ScmpArg(0, ScmpCmp.SCMP_CMP_EQ, 16, 0),
            ScmpArg(2, ScmpCmp.SCMP_CMP_EQ, 9, 0),
        ],
        "excludes": {"caps": [Capabilities.CAP_AUDIT_WRITE]},
        "names": ["socket"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(2, ScmpCmp.SCMP_CMP_NE, 9, 0)],
        "excludes": {"caps": [Capabilities.CAP_AUDIT_WRITE]},
        "names": ["socket"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(0, ScmpCmp.SCMP_CMP_NE, 16, 0)],
        "excludes": {"caps": [Capabilities.CAP_AUDIT_WRITE]},
        "names": ["socket"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "args": [ScmpArg(2, ScmpCmp.SCMP_CMP_NE, 9, 0)],
        "excludes": {"caps": [Capabilities.CAP_AUDIT_WRITE]},
        "names": ["socket"],
    },
    {
        "action": ScmpAction.SCMP_ACT_ALLOW,
        "includes": {"caps": [Capabilities.CAP_AUDIT_WRITE]},
        "names": ["socket"],
    },
]


DEFAULT_CAPABILITIES = [
    Capabilities.CAP_CHOWN,
    Capabilities.CAP_DAC_OVERRIDE,
    Capabilities.CAP_FOWNER,
    Capabilities.CAP_FSETID,
    Capabilities.CAP_KILL,
    Capabilities.CAP_SETGID,
    Capabilities.CAP_SETUID,
    Capabilities.CAP_SETPCAP,
    Capabilities.CAP_NET_BIND_SERVICE,
    Capabilities.CAP_SYS_CHROOT,
    Capabilities.CAP_SETFCAP,
]

EXTRA_CAPABILITIES = [
    Capabilities.CAP_NET_RAW,
    Capabilities.CAP_MKNOD,
    Capabilities.CAP_AUDIT_CONTROL,
]
